ProjectCore/ProjectCore/Controllers/StatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectCore.DAL.Models;

namespace ProjectCore.Controllers
{
    public class StatesController : Controller
    {
        private readonly ProjectCoreContext _context;

        public StatesController()
        {
            _context = new ProjectCoreContext();
        }

        // GET: States
        public async Task<IActionResult> Index()
        {
            return View(await _context.States.ToListAsync());
        }

        // GET: States/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var states = await _context.States
                .FirstOrDefaultAsync(m => m.Id == id);
            if (states == null)
            {
                return NotFound();
            }

            return View(states);
        }

        // GET: States/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: States/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Active")] States states)
        {
            if (ModelState.IsValid)
            {
                _context.Add(states);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(states);
        }

        // GET: States/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var states = await _context.States.FindAsync(id);
            if (states == null)
            {
                return NotFound();
            }
            return View(states);
        }

        // POST: States/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Active")] States states)
        {
            if (id != states.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(states);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatesExists(states.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(states);
        }

        // GET: States/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var states = await _context.States
                .FirstOrDefaultAsync(m => m.Id == id);
            if (states == null)
            {
                return NotFound();
            }

            return View(states);
        }

        // POST: States/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var states = await _context.States.FindAsync(id);
            _context.States.Remove(states);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatesExists(int id)
        {
            return _context.States.Any(e => e.Id == id);
        }
    }
}

ProjectCore/ProjectCore/Views/States/Create.cshtml
@model ProjectCore.DAL.Models.States

@{
    ViewData["Title"] = "Create";
}

    <h2>Create State</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary ">
                    <i class="fas fa-save"></i>
                </button>
                @Html.ActionLink("", "Index", "States", null, new { @class = "btn btn-primary fas fa-undo-alt" })


            </div>
        </form>
    </div>
</div>

ProjectCore/ProjectCore/Views/States/Delete.cshtml
@model ProjectCore.DAL.Models.States

@{
    ViewData["Title"] = "Delete";
}

    <h2>Delete States</h2>

<h3 class="badge badge-danger">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <table class="table table-bordered">
        <tr>

            <td>
                @Html.DisplayNameFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Active)
            </td>

        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.Active)
            </td>
        </tr>

    </table>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="submit" class="btn btn-primary ">
            <i class="fas fa-save"></i>
        </button>
        @Html.ActionLink("", "Index", "States", null, new { @class = "btn btn-primary fas fa-undo-alt" })

    </form>
</div>

ProjectCore/ProjectCore/Views/States/Details.cshtml
@model ProjectCore.DAL.Models.States

@{
    ViewData["Title"] = "Details";
}

    <h2>Details States</h2>

    <div>
        <hr />
        <table class="table table-bordered">
            <tr>

                <td>
                    @Html.DisplayNameFor(model => model.Name)
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.Active)
                </td>

            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Name)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Active)
                </td>
            </tr>

        </table>
    </div>
    <div>
        @Html.ActionLink("", "Edit", "States", new { Id = Model.Id }, new { @class = "btn btn-primary fas fa-edit" })

        @Html.ActionLink("", "Index", "States", null, new { @class = "btn btn-primary fas fa-undo-alt" })
    </div>

ProjectCore/ProjectCore/Views/States/Edit.cshtml
@model ProjectCore.DAL.Models.States

@{
    ViewData["Title"] = "Edit";
}

    <h2>Edit States</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary ">
                    <i class="fas fa-save"></i>
                </button>
                @Html.ActionLink("", "Index", "States", null, new { @class = "btn btn-primary fas fa-undo-alt" })



            </div>
        </form>
    </div>
</div>

ProjectCore/ProjectCore/Views/States/Index.cshtml
@model IEnumerable<ProjectCore.DAL.Models.States>

@{
    ViewData["Title"] = "Index";
}

<h2>States</h2>

@Html.ActionLink("", "Create", "States", null, new { @class = "btn btn-primary fas fa-plus-circle" })

<table class="table  table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                  

                    @Html.ActionLink("", "Edit", "States", new { id = item.Id }, new { @class = "btn btn-primary fas fa-edit" })

                    @Html.ActionLink("", "Details", "States", new { id = item.Id }, new { @class = "btn btn-primary fas fa-info-circle" })

                    @Html.ActionLink("", "Delete", "States", new { id = item.Id }, new { @class = "btn btn-primary fas fa-trash" })

                </td>
            </tr>
        }
    </tbody>
</table>