ProjectCore/ProjectCore/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Remotion.Linq.Parsing.ExpressionVisitors.MemberBindings;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ProjectCore.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;


        public ProjectsController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            IdentityUser user = await _userManager.FindByIdAsync(User.FindFirst(ClaimTypes.NameIdentifier).Value);

            Logica.BL.Tenants tenants = new Logica.BL.Tenants();
            var tenant = tenants.GetTenants(user.Id).FirstOrDefault();

            Logica.BL.Projects projects = new Logica.BL.Projects();
            var result = await _userManager.IsInRoleAsync(user, "Admin") ?
                projects.GetProjects(null, tenant.Id): 
                projects.GetProjects(null, tenant.Id, user.Id);

            var listProjects = result.Select(x => new Logica.Models.ViewModel.ProjectsIndexViewModel
                { 
                    Id = x.Id,
                    Title = x.Title,
                    Details = x.Details,
                    CreatedAt = x.CreatedAt,
                    ExpectedCompletionDate = x.ExpectedCompletionDate,
                    UpdateAt = x.UpdatedAt

            });

            listProjects = tenant.Plan.Equals("premium") ?
                listProjects :
                listProjects.Take(1).ToList();

            //ViewBag.listProjects = listProjects; more 1 models


            return View(listProjects);// return view has  the same name of action
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Create(Logica.Models.BindingModel.ProjectsCreateBindingModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await _userManager.FindByIdAsync(User.FindFirst(ClaimTypes.NameIdentifier).Value);

                Logica.BL.Tenants tenants = new Logica.BL.Tenants();
                var tenant = tenants.GetTenants(user.Id).FirstOrDefault();

                Logica.BL.Projects projects = new Logica.BL.Projects();
                projects.CreateProjects(model.Title, model.Details, model.ExpectedCompletionDate, tenant.Id);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Edit(int? id)
        {
            Logica.BL.Projects projects = new Logica.BL.Projects();

            var project = projects.GetProjects(id, null).FirstOrDefault();

            var projectBindingModel = new Logica.Models.BindingModel.ProjectsEditBindingModel
            {
                Id = project.Id,
                Details = project.Details,
                Title = project.Title,
                ExpectedCompletionDate= project.ExpectedCompletionDate



            };

            return View(projectBindingModel);
        }

        [HttpPost]
        public IActionResult Edit(Logica.Models.BindingModel.ProjectsEditBindingModel model )
        {
            if (ModelState.IsValid)
            {
                Logica.BL.Projects projects = new Logica.BL.Projects();
                projects.UpdateProjects(model.Id,
                    model.Title,
                    model.Details,
                    model.ExpectedCompletionDate
                    );
                return RedirectToAction("index");
            }

            return View(model);

        }

        public IActionResult Details(int? id)
        {

            Logica.BL.Projects projects = new Logica.BL.Projects();

            var project = projects.GetProjects(id, null).FirstOrDefault();
            var projectViewModel = new Logica.Models.ViewModel.ProjectsDetailsViewModel
            {
                Id = project.Id,
                Details = project.Details,
                Title = project.Title,
                ExpectedCompletionDate = project.ExpectedCompletionDate,
                CreatedAt = project.CreatedAt,
                UpdateAt = project.UpdatedAt
            };
            return View(projectViewModel);
        }

        public IActionResult Delete(int? id)
        {
            Logica.BL.Projects projects = new Logica.BL.Projects();

            projects.DeleteProjects(id);

            return RedirectToAction("index");
            //            return RedirectToAction("index", "Projects");
            // puedo redireccion a acciones de otros controladores
        }

    }
}

ProjectCore/ProjectCore/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ProjectCore.Controllers
{
    public class TasksController : Controller
    {
        public IActionResult Index(int? projectId)
        {
            Logica.BL.Tasks tasks = new Logica.BL.Tasks();

            var listTasks = tasks.GetTasks(projectId, null);

            var listTasksViewModel = listTasks.Select(x => new Logica.Models.ViewModel.TasksIndexViewModel
            {
                Id = x.Id,
                Title = x.Title,
                Details= x.Details,
                ExpirationDate = x.ExpirationDate,
                IsCompleted = x.IsCompleted,
                Effort = x.Effort,
                RemainingWork = x.RemainingWork,
                State = x.States.Name,
                Activity = x.Activities.Name,
                Priority = x.Priorities.Name



            });

            Logica.BL.Projects projects = new Logica.BL.Projects();
            var project = projects.GetProjects(projectId, null).FirstOrDefault();
            ViewBag.Project = project;
            return View(listTasksViewModel);
        }

        public IActionResult Create(int? projectId)
        {
            var taskBindingModel = new Logica.Models.BindingModel.TasksCreateBindingModel
            {
                ProjectId = projectId
            };

            Logica.BL.Activities activities = new Logica.BL.Activities();
            ViewBag.Activities = activities.GetActivities();

            Logica.BL.Priorities priorities = new Logica.BL.Priorities();
            ViewBag.Priorities = priorities.GetPriorities();

            Logica.BL.States states = new Logica.BL.States();
            ViewBag.states = states.GetStates();

            return View(taskBindingModel);
        }

        [HttpPost]
        public IActionResult create(Logica.Models.BindingModel.TasksCreateBindingModel model)
        {
            if (ModelState.IsValid)
            {
                Logica.BL.Tasks task = new Logica.BL.Tasks();
                task.CreateTasks(model.Title,
                    model.Details,
                    model.ExpirationDate,
                    model.IsCompleted,
                    model.Effort,
                    model.RemainingWork,
                    model.StateId,
                    model.ActivityId,
                    model.PriorityId,
                    model.ProjectId);

                return RedirectToAction("Index", new { projectId= model.ProjectId});
            }

            Logica.BL.Activities activities = new Logica.BL.Activities();
            ViewBag.Activities = activities.GetActivities();

            Logica.BL.Priorities priorities = new Logica.BL.Priorities();
            ViewBag.Priorities = priorities.GetPriorities();

            Logica.BL.States states = new Logica.BL.States();
            ViewBag.states = states.GetStates();

            return View(model);
        }
    }
}

ProjectCore/ProjectCore/Views/Projects/Create.cshtml
@model ProjectCore.Logica.Models.BindingModel.ProjectsCreateBindingModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form action="/Projects/Create" method="post">

    <div class="form-group">
        <div class="col-md-12">

            @Html.LabelFor(model => model.Title)
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

        </div>

    </div>


    <div class="form-group">
        <div class="col-md-12">

            @Html.LabelFor(model => model.Details)
            @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })

        </div>

    </div>



    <div class="form-group">
        <div class="col-md-12">

            @Html.LabelFor(model => model.ExpectedCompletionDate)
            @Html.EditorFor(model => model.ExpectedCompletionDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ExpectedCompletionDate, "", new { @class = "text-danger" })

        </div>

    </div>



    <div class="form-group">
        <div class="col-md-12">

            <button type="submit" class="btn btn-primary">

                <i class="fas fa-save"></i>
            </button>

            @Html.ActionLink(" ", "Index", "Projects", null, new { @class = "btn btn-primary fas fa-arrow-circle-left" })

        </div>

    </div>


</form>

ProjectCore/ProjectCore/Views/Projects/Details.cshtml
@model ProjectCore.Logica.Models.ViewModel.ProjectsDetailsViewModel
@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<table class="table table-bordered">
    <tr>

        <td>
            @Html.DisplayNameFor(model => model.Title)

        </td>
        <td>
            @Html.DisplayFor(model => model.Title)

        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.Details)
        </td>

        <td>
            @Html.DisplayFor(model => model.Details)

        </td>
    </tr>

    <tr>
        <td>
            @Html.DisplayNameFor(model => model.ExpectedCompletionDate)

        </td>
        <td>
            @Html.DisplayFor(model => model.ExpectedCompletionDate)

        </td>
    </tr>

    <tr>
        <td>
            @Html.DisplayNameFor(model => model.CreatedAt)

        </td>
        <td>
            @Html.DisplayFor(model => model.CreatedAt)

        </td>
    </tr>

    <tr>
        <td>
            @Html.DisplayNameFor(model => model.UpdateAt)

        </td>
        <td>
            @Html.DisplayFor(model => model.UpdateAt)

        </td>
    </tr>
</table>

<div class="form-group">
    <div class="col-md-12">
        @Html.ActionLink(" ", "Index", "Projects", null, new { @class = "btn btn-primary fas fa-arrow-circle-left" })

    </div>
</div>

ProjectCore/ProjectCore/Views/Projects/Edit.cshtml
@model ProjectCore.Logica.Models.BindingModel.ProjectsEditBindingModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form action="/Projects/Edit" method="post">
    @Html.HiddenFor(model => model.Id)


    <div class="form-group">
        <div class="col-md-12">

            @Html.LabelFor(model => model.Title)
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

        </div>

    </div>


    <div class="form-group">
        <div class="col-md-12">

            @Html.LabelFor(model => model.Details)
            @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })

        </div>

    </div>



    <div class="form-group">
        <div class="col-md-12">

            @Html.LabelFor(model => model.ExpectedCompletionDate)
            @Html.EditorFor(model => model.ExpectedCompletionDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ExpectedCompletionDate, "", new { @class = "text-danger" })

        </div>

    </div>



    <div class="form-group">
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">

                <i class="fas fa-save"></i>
            </button>
            @Html.ActionLink(" ", "Index", "Projects", null, new { @class = "btn btn-primary fas fa-arrow-circle-left" })

        </div>

    </div>


</form>

ProjectCore/ProjectCore/Views/Projects/Index.cshtml
@model IEnumerable<ProjectCore.Logica.Models.ViewModel.ProjectsIndexViewModel>
@{
    ViewData["Title"] = "Index";
}

<h2>Projects</h2>
<!--  los llamados con links por defecto diregen a un GET -->


@Html.ActionLink(" ", "Create", "Projects", null, new { @class = "btn btn-primary fas fa-plus-circle" })

<table class="table table-bordered">
    <tr>
        <td>Task</td>
        <td>
            @Html.DisplayNameFor(model => model.Title)

        </td>

        <td>
            @Html.DisplayNameFor(model => model.Details)

        </td>
        <td>
            @Html.DisplayNameFor(model => model.ExpectedCompletionDate)

        </td>
        <td>
            @Html.DisplayNameFor(model => model.CreatedAt)

        </td>
        <td>
            @Html.DisplayNameFor(model => model.UpdateAt)

        </td>
        <td></td>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.ActionLink(" ", "Index", "Tasks", new { projectId = item.Id }, new { @class = "btn btn-primary btn-sm fas fa-edit" })
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Title)


    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Details)


    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ExpectedCompletionDate)


    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CreatedAt)


    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UpdateAt)


    </td>
    <td>
        @Html.ActionLink(" ", "Edit", "Projects", new { id = item.Id }, new { @class = "btn btn-primary btn-sm fas fa-edit" })

        @Html.ActionLink(" ", "Details", "Projects", new { id = item.Id }, new { @class = "btn btn-primary btn-sm fas fa-info-circle" })

        @Html.ActionLink(" ", "Delete", "Projects", new { id = item.Id }, new { @class = "btn btn-primary btn-sm fas fa-trash" })


    </td>

</tr>
    }
</table>